"""create contrato_material_precos

Revision ID: 036e386a0c66
Revises: bb5ae900de46
Create Date: 2025-11-03 11:48:45.448888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036e386a0c66'
down_revision: Union[str, None] = 'bb5ae900de46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_material_precos',
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uom_id'], ['unidades_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'material_id', name='uq_contrato_material')
    )
    op.create_index(op.f('ix_contrato_material_precos_contrato_id'), 'contrato_material_precos', ['contrato_id'], unique=False)
    op.create_index(op.f('ix_contrato_material_precos_id'), 'contrato_material_precos', ['id'], unique=False)
    op.create_index(op.f('ix_contrato_material_precos_material_id'), 'contrato_material_precos', ['material_id'], unique=False)
    op.create_index(op.f('ix_contrato_material_precos_uom_id'), 'contrato_material_precos', ['uom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contrato_material_precos_uom_id'), table_name='contrato_material_precos')
    op.drop_index(op.f('ix_contrato_material_precos_material_id'), table_name='contrato_material_precos')
    op.drop_index(op.f('ix_contrato_material_precos_id'), table_name='contrato_material_precos')
    op.drop_index(op.f('ix_contrato_material_precos_contrato_id'), table_name='contrato_material_precos')
    op.drop_table('contrato_material_precos')
    # ### end Alembic commands ###
