"""create fornecedores table

Revision ID: 0c747e0483a1
Revises: 395ed787b089
Create Date: 2025-10-27 11:10:04.347293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c747e0483a1'
down_revision: Union[str, None] = '395ed787b089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('contato', sa.String(length=120), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=False)
    op.create_index(op.f('ix_fornecedores_email'), 'fornecedores', ['email'], unique=False)
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_index(op.f('ix_fornecedores_nome'), 'fornecedores', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fornecedores_nome'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_email'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
