"""create orcamentos base

Revision ID: 112165ec8c26
Revises: 036e386a0c66
Create Date: 2025-11-05 11:10:29.978102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112165ec8c26'
down_revision: Union[str, None] = '036e386a0c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamentos',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('moeda', sa.String(length=8), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('acrescimo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamentos_cliente_id'), 'orcamentos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_orcamentos_contrato_id'), 'orcamentos', ['contrato_id'], unique=False)
    op.create_index(op.f('ix_orcamentos_id'), 'orcamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orcamentos_id'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_contrato_id'), table_name='orcamentos')
    op.drop_index(op.f('ix_orcamentos_cliente_id'), table_name='orcamentos')
    op.drop_table('orcamentos')
    # ### end Alembic commands ###
