"""create tipos_servico table

Revision ID: 57f0a1b0e5cd
Revises: 0c747e0483a1
Create Date: 2025-10-29 10:01:07.483855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f0a1b0e5cd'
down_revision: Union[str, None] = '0c747e0483a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_servico',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_servico_id'), 'tipos_servico', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_servico_nome'), 'tipos_servico', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_servico_nome'), table_name='tipos_servico')
    op.drop_index(op.f('ix_tipos_servico_id'), table_name='tipos_servico')
    op.drop_table('tipos_servico')
    # ### end Alembic commands ###
