"""create unidades_medida table

Revision ID: 93341f86414b
Revises: 57f0a1b0e5cd
Create Date: 2025-10-29 10:35:11.130376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93341f86414b'
down_revision: Union[str, None] = '57f0a1b0e5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidades_medida',
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('simbolo', sa.String(length=16), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_medida_id'), 'unidades_medida', ['id'], unique=False)
    op.create_index(op.f('ix_unidades_medida_nome'), 'unidades_medida', ['nome'], unique=True)
    op.create_index(op.f('ix_unidades_medida_simbolo'), 'unidades_medida', ['simbolo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unidades_medida_simbolo'), table_name='unidades_medida')
    op.drop_index(op.f('ix_unidades_medida_nome'), table_name='unidades_medida')
    op.drop_index(op.f('ix_unidades_medida_id'), table_name='unidades_medida')
    op.drop_table('unidades_medida')
    # ### end Alembic commands ###
