"""create orcamento_itens

Revision ID: 9e90f77d4d8c
Revises: 112165ec8c26
Create Date: 2025-11-14 09:46:54.616774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e90f77d4d8c'
down_revision: Union[str, None] = '112165ec8c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento_itens',
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('item_tipo', sa.String(length=16), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=True),
    sa.Column('tipo_hh', sa.String(length=16), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=180), nullable=True),
    sa.Column('uom_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_item', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['unidades_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamento_itens_id'), 'orcamento_itens', ['id'], unique=False)
    op.create_index(op.f('ix_orcamento_itens_maquina_id'), 'orcamento_itens', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_orcamento_itens_material_id'), 'orcamento_itens', ['material_id'], unique=False)
    op.create_index(op.f('ix_orcamento_itens_orcamento_id'), 'orcamento_itens', ['orcamento_id'], unique=False)
    op.create_index(op.f('ix_orcamento_itens_uom_id'), 'orcamento_itens', ['uom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orcamento_itens_uom_id'), table_name='orcamento_itens')
    op.drop_index(op.f('ix_orcamento_itens_orcamento_id'), table_name='orcamento_itens')
    op.drop_index(op.f('ix_orcamento_itens_material_id'), table_name='orcamento_itens')
    op.drop_index(op.f('ix_orcamento_itens_maquina_id'), table_name='orcamento_itens')
    op.drop_index(op.f('ix_orcamento_itens_id'), table_name='orcamento_itens')
    op.drop_table('orcamento_itens')
    # ### end Alembic commands ###
