"""create contrato_hh_precos

Revision ID: bb5ae900de46
Revises: e3f13b83b909
Create Date: 2025-11-03 10:56:41.470580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5ae900de46'
down_revision: Union[str, None] = 'e3f13b83b909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_hh_precos',
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('tipo_hh', sa.String(length=16), nullable=False),
    sa.Column('preco_hora', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uom_id'], ['unidades_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'maquina_id', 'tipo_hh', name='uq_contrato_maquina_tipo')
    )
    op.create_index(op.f('ix_contrato_hh_precos_contrato_id'), 'contrato_hh_precos', ['contrato_id'], unique=False)
    op.create_index(op.f('ix_contrato_hh_precos_id'), 'contrato_hh_precos', ['id'], unique=False)
    op.create_index(op.f('ix_contrato_hh_precos_maquina_id'), 'contrato_hh_precos', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_contrato_hh_precos_uom_id'), 'contrato_hh_precos', ['uom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contrato_hh_precos_uom_id'), table_name='contrato_hh_precos')
    op.drop_index(op.f('ix_contrato_hh_precos_maquina_id'), table_name='contrato_hh_precos')
    op.drop_index(op.f('ix_contrato_hh_precos_id'), table_name='contrato_hh_precos')
    op.drop_index(op.f('ix_contrato_hh_precos_contrato_id'), table_name='contrato_hh_precos')
    op.drop_table('contrato_hh_precos')
    # ### end Alembic commands ###
