"""create contratos table

Revision ID: e3f13b83b909
Revises: f22c727dfe4b
Create Date: 2025-10-31 11:18:57.120245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f13b83b909'
down_revision: Union[str, None] = 'f22c727dfe4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('moeda', sa.String(length=8), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('hh_regular_default', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hh_extra_default', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hh_feriado_default', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('material_kg_default', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_cliente_id'), 'contratos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_index(op.f('ix_contratos_cliente_id'), table_name='contratos')
    op.drop_table('contratos')
    # ### end Alembic commands ###
