"""create materiais e maquinas

Revision ID: f22c727dfe4b
Revises: 93341f86414b
Create Date: 2025-10-31 09:12:33.554186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22c727dfe4b'
down_revision: Union[str, None] = '93341f86414b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquinas',
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('uom_hh_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uom_hh_id'], ['unidades_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maquinas_id'), 'maquinas', ['id'], unique=False)
    op.create_index(op.f('ix_maquinas_nome'), 'maquinas', ['nome'], unique=True)
    op.create_index(op.f('ix_maquinas_uom_hh_id'), 'maquinas', ['uom_hh_id'], unique=False)
    op.create_table('materiais',
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('uom_base_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uom_base_id'], ['unidades_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiais_id'), 'materiais', ['id'], unique=False)
    op.create_index(op.f('ix_materiais_nome'), 'materiais', ['nome'], unique=True)
    op.create_index(op.f('ix_materiais_uom_base_id'), 'materiais', ['uom_base_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materiais_uom_base_id'), table_name='materiais')
    op.drop_index(op.f('ix_materiais_nome'), table_name='materiais')
    op.drop_index(op.f('ix_materiais_id'), table_name='materiais')
    op.drop_table('materiais')
    op.drop_index(op.f('ix_maquinas_uom_hh_id'), table_name='maquinas')
    op.drop_index(op.f('ix_maquinas_nome'), table_name='maquinas')
    op.drop_index(op.f('ix_maquinas_id'), table_name='maquinas')
    op.drop_table('maquinas')
    # ### end Alembic commands ###
